# Generated by Django 3.1.7 on 2021-03-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_midi_melody'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Midi',
            new_name='Midi1',
        ),
    ]
