# Generated by Django 3.1.7 on 2021-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(max_length=50, verbose_name='Tempo')),
                ('instrument', models.CharField(max_length=50, verbose_name='Instrument')),
                ('repeats', models.CharField(max_length=50, verbose_name='Repeats')),
                ('track', models.CharField(max_length=50, verbose_name='Track')),
                ('mood', models.CharField(max_length=50, verbose_name='Mood')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Music',
            },
        ),
    ]
