# Generated by Django 3.1.7 on 2021-03-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='melody',
            field=models.CharField(default=150, max_length=150, verbose_name='Melody'),
            preserve_default=False,
        ),
    ]
